# Configuration for unfolding analysis of observables 
#
# The observables are structured into observable blocks (e.g. theta_g, subjet_z, etc.)
# each containing multiple individual subconfigurations (e.g. zcut, beta, subjetR, etc.),
# where each subconfiguration corresponds to a single observable to be calculated.
# One can also specify a list of jetR, which will be looped over.

analysis_observables:
  jet_pt: [config1]
  theta_g: [config1, config2]
  zg: [config1, config2]
  leading_subjet_z: [config1, config2]
  jet_axis: [config1]
  ang: [config1, config3, config5, config7]

jetR: [0.4]

# Observable block
jet_pt:

  common_settings:
    xtitle: '#it{p}_{T}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{p}_{T}}'
    pt_bins_reported: [20, 40, 60, 80, 120]

  config1:
    obs_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    obs_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]

# Observable block
theta_g:

  common_settings:
    xtitle: '#it{#theta}_{g}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{#theta}_{g}}'
      
  config1:
    SoftDrop:
      zcut: 0.1
      beta: 0
    obs_bins_truth: [0., 0.1, 0.17, 0.23, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0]
    obs_bins_det: [0., 0.1, 0.15, 0.2, 0.25, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0]

  config2:
    SoftDrop:
      zcut: 0.2
      beta: 0
    obs_bins_truth: [0., 0.15, 0.25, 0.32, 0.4, 0.5, 0.6, 0.7, 0.8, 1.0]
    obs_bins_det: [0., 0.15, 0.25, 0.3, 0.35, 0.4, 0.5, 0.6, 0.7, 0.8, 1.0]

# Observable block
zg:

  common_settings:
    xtitle: '#it{z}_{g}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{z}_{g}}'
      
  config1:
    SoftDrop:
      zcut: 0.1
      beta: 0
    obs_bins_truth: [0.1, 0.13, 0.16, 0.2, 0.25, 0.3, 0.35, 0.4, 0.5]
    obs_bins_det: [0.1, 0.13, 0.16, 0.2, 0.25, 0.3, 0.35, 0.4, 0.5]

  config2:
    SoftDrop:
      zcut: 0.2
      beta: 0
    obs_bins_truth: [0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]
    obs_bins_det: [0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]

# Observable block
leading_subjet_z:

  common_settings:
    xtitle: '#it{z_{r}}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{z_{r}}}'

  config1:
    subjet_R: 0.1
    obs_bins_truth: [0., 0.6, 0.7, 0.77, 0.83, 0.89, 0.95, 1.0]
    obs_bins_det: [0., 0.6, 0.7, 0.77, 0.83, 0.89, 0.95, 1.0]
    
  config2:
    subjet_R: 0.2
    obs_bins_truth: [0., 0.7, 0.8, 0.86, 0.9, 0.94, 0.98, 1.0]
    obs_bins_det: [0., 0.7, 0.8, 0.86, 0.9, 0.94, 0.98, 1.0]

# Observable block
jet_axis:

  common_settings:
    xtitle: '#it{#Delta R}'
    ytitle: '#frac{1}{#it{N}_{jets}} #frac{d#it{N}}{d#Delta R}'
      
  config1:
    axis: 'Standard_WTA'
    obs_bins_truth: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.08, 0.1, 0.15, 0.2]
    obs_bins_det: [0., 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.06, 0.07, 0.08, 0.1, 0.15, 0.2, 0.3, 0.4]
      
  config2:
    axis: 'Standard_SD'
    SoftDrop:
      zcut: 0.1
      beta: 0
    obs_bins_truth: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.1, 0.2] # 0.001
    obs_bins_det: [0., 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.06, 0.1, 0.2, 0.3, 0.4] # 0.001
      
  config3:
    axis: 'WTA_SD'
    SoftDrop:
      zcut: 0.1
      beta: 0
    obs_bins_truth: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.08, 0.1, 0.15, 0.2]
    obs_bins_det: [0., 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.06, 0.07, 0.08, 0.1, 0.15, 0.2, 0.3, 0.4]

# Observable block
ang:

  common_settings:
    xtitle: '#it{#lambda}_{#it{#beta}}^{#it{#kappa}=1}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{#lambda}_{#it{#beta}}^{#it{#kappa}=1}}'

  config1:
    beta: 1
    obs_bins_truth: [0, 0.06, 0.09, 0.12, 0.15, 0.18, 0.22, 0.26, 0.3, 0.35, 0.45, 0.6, 0.75]
    obs_max_reported: [0.6]
    obs_bins_det: [0, 0.06, 0.09, 0.12, 0.15, 0.18, 0.22, 0.26, 0.3, 0.35, 0.45, 0.6, 0.75]

  config2:
    beta: 1.5
    obs_bins_truth: [0, 0.03, 0.05, 0.07, 0.09, 0.11, 0.13, 0.15, 0.19, 0.24, 0.32, 0.5, 0.75]
    obs_max_reported: [0.5]
    obs_bins_det: [0, 0.03, 0.05, 0.065, 0.08, 0.095, 0.11, 0.13, 0.15, 0.19, 0.24, 0.32, 0.5, 0.75]

  config3:
    beta: 2
    obs_bins_truth: [0, 0.02, 0.035, 0.05, 0.065, 0.08, 0.1, 0.14, 0.18, 0.25, 0.4, 0.55]
    obs_max_reported: [0.4]
    obs_bins_det: [0, 0.02, 0.035, 0.05, 0.065, 0.08, 0.1, 0.14, 0.18, 0.25, 0.40, 0.55]

  config4:
    beta: 3
    obs_bins_truth: [0, 0.008, 0.015, 0.025, 0.035, 0.045, 0.06, 0.08, 0.11, 0.16, 0.3, 0.4]
    obs_max_reported: [0.3]
    obs_bins_det: [0, 0.008, 0.015, 0.025, 0.035, 0.045, 0.06, 0.08, 0.11, 0.16, 0.3, 0.4]

  config5:
    SoftDrop:
      zcut: 0.2
      beta: 0
    beta: 1
    obs_bins_truth: [0, 0.03, 0.05, 0.07, 0.1, 0.13, 0.16, 0.2, 0.25, 0.3, 0.35, 0.4,
                     0.45, 0.5, 0.6, 0.8]
    obs_max_reported: [0.6]
    obs_bins_det: [0, 0.03, 0.05, 0.07, 0.1, 0.13, 0.16, 0.2, 0.25, 0.3, 0.35, 0.4,
                   0.45, 0.5, 0.6, 0.8]

  config6:
    SoftDrop:
      zcut: 0.2
      beta: 0
    beta: 1.5
    obs_bins_truth: [0, 0.004, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.075, 0.09, 0.12, 0.15,
                     0.2, 0.25, 0.3, 0.5, 0.75]
    obs_max_reported: [0.5]
    obs_bins_det: [0, 0.004, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.075, 0.09, 0.12, 0.15,
                   0.2, 0.25, 0.3, 0.5, 0.75]

  config7:
    SoftDrop:
      zcut: 0.2
      beta: 0
    beta: 2
    obs_bins_truth: [0, 0.001, 0.003, 0.006, 0.01, 0.02, 0.04, 0.06, 0.09, 0.12, 0.15, 0.2, 0.4, 0.6]
    obs_max_reported: [0.4]
    obs_bins_det: [0, 0.001, 0.003, 0.006, 0.01, 0.02, 0.04, 0.06, 0.09, 0.12, 0.15, 0.2, 0.4, 0.6]

  config8:
    SoftDrop:
      zcut: 0.2
      beta: 0
    beta: 3
    obs_bins_truth: [0, 0.001, 0.003, 0.006, 0.01, 0.015, 0.025, 0.04, 0.06, 0.08, 0.1, 0.3, 0.5]
    obs_max_reported: [0.3]
    obs_bins_det: [0, 0.001, 0.003, 0.006, 0.01, 0.015, 0.025, 0.04, 0.06, 0.08, 0.1, 0.3, 0.5]

###############################################################################
# Analysis parameters

# Directory to write analysis output to
output_dir: '/rstorage/alice/AnalysisResults/james/1107540/output_analysis/'

# Set which analysis steps to perform
do_plot_observables: True
do_unfolding: False
do_systematics: False
do_plot_final_result: False

# List of which systematics to perform
systematics_list:
  - main
  - trkeff
  - fastsim_generator0
  - fastsim_generator1

# Paths to processing output, to be used for unfolding
main_data: '/rstorage/alice/AnalysisResults/james/1107540/processing_output_merged.h5'
main_response: '/rstorage/alice/AnalysisResults/james/1107541/processing_output_merged.h5'
trkeff_response: ''
fastsim_response:
 - ''
 - ''

 # Figure info
file_format: '.pdf'
figure_approval_status: 'WIP'
