# Configuration for:
#   (a) Processing of ROOT trees into histograms
#   (b) Analysis of histograms into final result
#
# The observables are structured into observable blocks (e.g. theta_g, subjet_z, etc.)
# each containing multiple individual subconfigurations (e.g. zcut, beta, subjetR, etc.),
# where each subconfiguration corresponds to a single observable to be calculated.
# One can also specify a list of jetR, which will be looped over.

process_observables: ['theta_g', 'zg', 'leading_subjet_z', 'jet_axis', 'ang']
jetR: [0.4]
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
reject_tracks_fraction: 0.0
eta_max: 0.9
debug_level: 0
fast_simulation: False
#event_number_max: 1000

# Observable block
theta_g:

  common_settings:
    xtitle: '#it{#theta}_{g}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{#theta}_{g}}'
    pt_bins_reported: [60, 80]
      
  config1:
    SoftDrop:
      zcut: 0.1
      beta: 0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.1, 0.17, 0.23, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0]
    obs_bins_det: [0., 0.1, 0.15, 0.2, 0.25, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0]
    obs_bins_det_sys_binning: [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.8, 0.9, 1.0]

  config2:
    SoftDrop:
      zcut: 0.2
      beta: 0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.15, 0.25, 0.32, 0.4, 0.5, 0.6, 0.7, 0.8, 1.0]
    obs_bins_det: [0., 0.15, 0.25, 0.3, 0.35, 0.4, 0.5, 0.6, 0.7, 0.8, 1.0]
    obs_bins_det_sys_binning: [0., 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.9, 1.0]

# Observable block
zg:

  common_settings:
    xtitle: '#it{z}_{g}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{z}_{g}}'
    pt_bins_reported: [60, 80]
      
  config1:
    SoftDrop:
      zcut: 0.1
      beta: 0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0.1, 0.13, 0.16, 0.2, 0.25, 0.3, 0.35, 0.4, 0.5]
    obs_bins_det: [0.1, 0.13, 0.16, 0.2, 0.25, 0.3, 0.35, 0.4, 0.5]
    obs_bins_det_sys_binning: [0.1, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22, 0.25, 0.28, 0.31, 0.34, 0.37, 0.4, 0.43, 0.46, 0.5]

  config2:
    SoftDrop:
      zcut: 0.2
      beta: 0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]
    obs_bins_det: [0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]
    obs_bins_det_sys_binning: [0.2, 0.22, 0.25, 0.28, 0.31, 0.34, 0.37, 0.4, 0.43,   0.46, 0.5]

# Observable block
leading_subjet_z:

  common_settings:
    xtitle: '#it{z_{r}}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{z_{r}}}'
    pt_bins_reported: [80, 120]

  config1:
    subjet_R: 0.1
    pt_bins_truth: [5, 20, 40, 60, 80, 120, 150, 200]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120, 150]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    obs_bins_truth: [0., 0.6, 0.7, 0.77, 0.83, 0.89, 0.95, 1.0]
    obs_bins_det: [0., 0.6, 0.7, 0.77, 0.83, 0.89, 0.95, 1.0]
    obs_bins_det_sys_binning: [0., 0.5, 0.6, 0.7, 0.8, 0.9, 0.93, 0.95, 0.96, 0.97, 0.98, 0.99, 1.0]
    
  config2:
    subjet_R: 0.2
    pt_bins_truth: [5, 20, 40, 60, 80, 120, 150, 200]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120, 150]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    obs_bins_truth: [0., 0.7, 0.8, 0.86, 0.9, 0.94, 0.98, 1.0]
    obs_bins_det: [0., 0.7, 0.8, 0.86, 0.9, 0.94, 0.98, 1.0]
    obs_bins_det_sys_binning: [0., 0.5, 0.6, 0.7, 0.8, 0.9, 0.93, 0.95, 0.96, 0.97, 0.98, 0.99, 1.0]

# Observable block
jet_axis:

  common_settings:
    xtitle: '#it{#Delta R}'
    ytitle: '#frac{1}{#it{N}_{jets}} #frac{d#it{N}}{d#Delta R}'
    pt_bins_reported: [20, 40, 60, 80]
      
  config1:
    axis: 'Standard_WTA'
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.08, 0.1, 0.15, 0.2]
    obs_bins_det: [0., 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.06, 0.07, 0.08, 0.1, 0.15, 0.2, 0.3, 0.4]
    obs_bins_det_sys_binning: [0., 0.006, 0.011, 0.016, 0.021, 0.026, 0.032, 0.04, 0.048, 0.06, 0.07, 0.08, 0.1, 0.15, 0.2, 0.3, 0.4]
      
  config2:
    axis: 'Standard_SD'
    SoftDrop:
      zcut: 0.1
      beta: 0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.1, 0.2] # 0.001
    obs_bins_det: [0., 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.06, 0.1, 0.2, 0.3, 0.4] # 0.001
    obs_bins_det_sys_binning: [0., 0.006, 0.011, 0.016, 0.021, 0.026, 0.032, 0.04, 0.048, 0.06, 0.1, 0.2, 0.3, 0.4]
      
  config3:
    axis: 'WTA_SD'
    SoftDrop:
      zcut: 0.1
      beta: 0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.08, 0.1, 0.15, 0.2]
    obs_bins_det: [0., 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.06, 0.07, 0.08, 0.1, 0.15, 0.2, 0.3, 0.4]
    obs_bins_det_sys_binning: [0., 0.006, 0.011, 0.016, 0.021, 0.026, 0.032, 0.04, 0.048, 0.06, 0.07, 0.08, 0.1, 0.15, 0.2, 0.3, 0.4]

# Observable block
ang:

  common_settings:
    xtitle: '#it{#lambda}_{#it{#beta}}^{#it{#kappa}=1}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{#lambda}_{#it{#beta}}^{#it{#kappa}=1}}'
    pt_bins_reported: [40, 60]

  config1:
    beta: 1
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.06, 0.09, 0.12, 0.15, 0.18, 0.22, 0.26, 0.3, 0.35, 0.45, 0.6, 0.75]
    obs_max_reported: [0.6]
    obs_bins_det: [0, 0.06, 0.09, 0.12, 0.15, 0.18, 0.22, 0.26, 0.3, 0.35, 0.45, 0.6, 0.75]
    obs_bins_det_sys_binning: [0, 0.05, 0.1, 0.13, 0.17, 0.21, 0.25, 0.32, 0.36, 0.41,
                               0.51, 0.62, 0.75]

  config2:
    beta: 1.5
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.03, 0.05, 0.07, 0.09, 0.11, 0.13, 0.15, 0.19, 0.24, 0.32, 0.5, 0.75]
    obs_max_reported: [0.5]
    obs_bins_det: [0, 0.03, 0.05, 0.065, 0.08, 0.095, 0.11, 0.13, 0.15, 0.19, 0.24, 0.32, 0.5, 0.75]
    obs_bins_det_sys_binning: [0, 0.035, 0.055, 0.075, 0.095, 0.12, 0.14, 0.16, 0.18, 0.20, 0.22,
                               0.27, 0.35, 0.5, 0.75]

  config3:
    beta: 2
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.02, 0.035, 0.05, 0.065, 0.08, 0.1, 0.14, 0.18, 0.25, 0.4, 0.55]
    obs_max_reported: [0.4]
    obs_bins_det: [0, 0.02, 0.035, 0.05, 0.065, 0.08, 0.1, 0.14, 0.18, 0.25, 0.40, 0.55]
    obs_bins_det_sys_binning: [0, 0.01, 0.03, 0.045, 0.065, 0.085, 0.11, 0.13, 0.17, 0.27, 0.43, 0.55]

  config4:
    beta: 3
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.008, 0.015, 0.025, 0.035, 0.045, 0.06, 0.08, 0.11, 0.16, 0.3, 0.4]
    obs_max_reported: [0.3]
    obs_bins_det: [0, 0.008, 0.015, 0.025, 0.035, 0.045, 0.06, 0.08, 0.11, 0.16, 0.3, 0.4]
    obs_bins_det_sys_binning: [0, 0.01, 0.02, 0.03, 0.04, 0.055, 0.065, 0.085, 0.1, 0.17, 0.28, 0.4]

  config5:
    SoftDrop:
      zcut: 0.2
      beta: 0
    beta: 1
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.03, 0.05, 0.07, 0.1, 0.13, 0.16, 0.2, 0.25, 0.3, 0.35, 0.4,
                     0.45, 0.5, 0.6, 0.8]
    obs_max_reported: [0.6]
    obs_bins_det: [0, 0.03, 0.05, 0.07, 0.1, 0.13, 0.16, 0.2, 0.25, 0.3, 0.35, 0.4,
                   0.45, 0.5, 0.6, 0.8]
    obs_bins_det_sys_binning: [0, 0.04, 0.07, 0.11, 0.16, 0.21, 0.26, 0.32, 0.38, 0.45, 0.62, 0.8]

  config6:
    SoftDrop:
      zcut: 0.2
      beta: 0
    beta: 1.5
    pt_bins_truth:  [5, 10, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.004, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.075, 0.09, 0.12, 0.15,
                     0.2, 0.25, 0.3, 0.5, 0.75]
    obs_max_reported: [0.5]
    obs_bins_det: [0, 0.004, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.075, 0.09, 0.12, 0.15,
                   0.2, 0.25, 0.3, 0.5, 0.75]
    obs_bins_det_sys_binning: [0, 0.005, 0.01, 0.015, 0.025, 0.035, 0.045, 0.055, 0.065, 0.08,
                               0.1, 0.13, 0.15, 0.21, 0.26, 0.32, 0.52, 0.75]

  config7:
    SoftDrop:
      zcut: 0.2
      beta: 0
    beta: 2
    pt_bins_truth:  [5, 10, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.001, 0.003, 0.006, 0.01, 0.02, 0.04, 0.06, 0.09, 0.12, 0.15, 0.2, 0.4, 0.6]
    obs_max_reported: [0.4]
    obs_bins_det: [0, 0.001, 0.003, 0.006, 0.01, 0.02, 0.04, 0.06, 0.09, 0.12, 0.15, 0.2, 0.4, 0.6]
    obs_bins_det_sys_binning: [0, 0.002, 0.005, 0.01, 0.015, 0.025, 0.035, 0.045, 0.07, 0.1,
                               0.13, 0.16, 0.21, 0.42, 0.6]

  config8:
    SoftDrop:
      zcut: 0.2
      beta: 0
    beta: 3
    pt_bins_truth:  [5, 10, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.001, 0.003, 0.006, 0.01, 0.015, 0.025, 0.04, 0.06, 0.08, 0.1, 0.3, 0.5]
    obs_max_reported: [0.3]
    obs_bins_det: [0, 0.001, 0.003, 0.006, 0.01, 0.015, 0.025, 0.04, 0.06, 0.08, 0.1, 0.3, 0.5]
    obs_bins_det_sys_binning: [0, 0.001, 0.002, 0.005, 0.01, 0.015, 0.03, 0.045, 0.065,
                               0.08, 0.1, 0.14, 0.28, 0.5]

###############################################################################
# Analysis parameters

file_format: '.pdf'
output_dir: '/Users/jamesmulligan/Analysis_subjet_z/output_analysis/pp/493677-04-paper'
roounfold_path: '/Users/jamesmulligan/heppy/external/roounfold/roounfold-current/lib/libRooUnfold.dylib'

analysis_observable: 'leading_subjet_z'
do_unfolding: False
force_rebin: True
do_systematics: True
do_plot_final_result: True
do_plot_performance: False
figure_approval_status: ''

# List of which systematics to perform
systematics_list:
  - main
  - trkeff
  - prior1
  - prior2
  - truncation
  - binning
  - fastsim_generator0
  - fastsim_generator1
#  - delta_matching      # Note: only include for inclusive case

# Paths to processing output, to be used for unfolding
main_data: '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC17pq/493677/AnalysisResultsFinal.root'
main_response: '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC18b8/493678/AnalysisResultsFinal.root'
trkeff_response: '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC18b8_trkeff/493679/AnalysisResultsFinal.root'
delta_matching_response: '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC18b8_matching/821755/AnalysisResultsFinal.root'
fastsim_response:
 - '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC18b8_fastsim_pythia/493680/AnalysisResultsFinal.root'
 - '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC18b8_fastsim_herwig/493681/AnalysisResultsFinal.root'

# Prior variation parameters
#prior_variation_option: 4              # Leading subjets
prior_variation_option: 1             # Inclusive subjets
prior1_variation_parameter: 0.5
prior2_variation_parameter: -0.5
